---
title: calculate_functional_diversity
date: 2024
type: reference
tags: " #code/R "
description: "Code for calculating functional diversity in R"
---
**Original Script by Dr. Brendan Casey**
**Script modified by ILT**
Methods by:
Laliberté, E.; Legendre, P.; Shipley, B. FD: Measuring Functional Diversity from Multiple Traits, and Other Tools for Functional Ecology. R Package Version 1.0-12. 2014. Available online: <https://cran.r-project.org/web/packages/FD>.

Trait data can be accessed in R using https://github.com/RS-eco/traitdata.

# Load packages
```R 
# Get functional traits from the traitdata package
# install.packages("r2glmm")
# library(remotes)
# remotes::install_github("RS-eco/traitdata")
library(traitdata)
##Load packages----
library(FD)
library(tidyverse)
library(dplyr)
library(readr)
library(mgcv)
library(glmmTMB)
library(DHARMa)
library(vegan)
library(ggplot2)
library(patchwork)
library(sjPlot)
library(MuMIn)
library(r2glmm)
library(lme4)
library(dampack)
library(car)
library(MuMIn)
library(glue)
```

# Community metrics

## Calculate Diversity
Calculate functional diversity using the `FD` package in R:
```R
#Setup ----

##Import data----
## Load community data

abundance_data <- read_csv("0_Data/Processed/community_abundance_by_location_common_names - matching names.csv") 
View(abundance_data)
## Get the trait data----
trait_data_all_birds <- elton_birds
# write.csv(trait_data, "0_Data/Processed/trait data.csv")

### Create dataframe where rows are indexed by species, columns are traits----
# 1. create list from abundance columns
# Extract species names starting from the 6th column
my_species <- colnames(abundance_data)[6:length(colnames(abundance_data))]

# No Pacific Wren data in the trait data, also only 1 detection
my_species <- my_species[my_species != "Pacific Wren"]
abundance_data <- abundance_data %>% select(-c("Pacific Wren", "Wilson's Snipe"))

# Filter trait data for desired birds
trait_data_select_birds <- trait_data_all_birds |>
                              filter(English %in% my_species)

species_found <- trait_data_select_birds$English
# Find items in list1 that are not in list2
missing_in_list2 <- setdiff(species_names, species_found)

# Find items in list2 that are not in list1 (if needed)
missing_in_list1 <- setdiff(species_found, species_names)

# renamed: Clay-coloured sparrow, Canada Jay, LeConte's Sparrow, Western Wood-Pewee,
# Dusky Flycatcher, Brown Creeper to American Treecreeper, European Starling to Common Starling, 
# no trait data: Wilsons snipe, Pacific Wren
# Printing the results
print(missing_in_list2)
print(missing_in_list1)

### Trim trait dataframe as:
#|species|diet.inv|diet.vend|diet.vect|diet.seed|forestStrat.groud|
# trait_dataframe <- trait_data_select_birds %>%
#                     select(English, Diet.Inv, Diet.Vend, Diet.Vect, Diet.Seed, ForStrat.ground)
names(trait_data_select_birds)[names(trait_data_select_birds) == "English"] <- "Species_common"

### Load dataframe with site level detection data----
# |site|year|ALFL|AMBI|AMCO|AMCR|AMKE|AMPI|...|
detection_data <- abundance_data[, !(names(abundance_data) %in% c("latitude", "longitude", "species_code"))]
View(detection_data)
#Set up traits dataframe ----
##Keep only traits of interest----
trait_data<-trait_data_select_birds%>%
  dplyr::select(c("Species_common", "Diet.Inv", "Diet.Vend",
                  "Diet.Vect", "Diet.Vfish", "Diet.Vunk",
                  "Diet.Scav", "Diet.Fruit", "Diet.Nect",
                  "Diet.Seed", "Diet.PlantO", "Diet.5Cat",
                  "ForStrat.watbelowsurf", "ForStrat.wataroundsurf", "ForStrat.ground",
                  "ForStrat.understory", "ForStrat.midhigh", "ForStrat.canopy",
                  "ForStrat.aerial", "PelagicSpecialist", "Nocturnal",
                  "BodyMass.Value"))%>%
  arrange(trait_data_select_birds)
# names(trait_data)[names(trait_data) == "English"] <- "Species_common"

## If you need to, set species codes as rownames in trait dataframe----
#View(trait_data)
#traits<- bd_tr[,-1]
#rownames(traits) <- bd_tr[,1]

##////////////////////////////////////////////////////////////////

# Setup detection matrix----
# abund<-x
##remove site and year fields----
#you should have a dataframe with only species detection columns. E.g:
#|ALFL|AMBI|AMCO|AMCR|AMKE|AMPI|...|
# Get rid of datetime
abund1<-detection_data[-c(2:2)]
View(abund1)
# Set sites names as the row names
# Set row names
abund1 <- as.data.frame(abund1)
rownames(abund1) <- abund1$location

# Remove the original column
abund1$location <- NULL

##covert dataframe to matrix----
# abund2<-data.matrix(head(abund1))
# abund2 <- as.matrix(abund1)
abund2 <- abund1[, order(colnames(abund1))]
# Get rid of trait speices dupplicates
trait_data <- trait_data %>% distinct(Species_common, .keep_all = TRUE)

# Reorder alphabetically the species
trait_data <- trait_data[order(trait_data$Species_common, decreasing = FALSE), ]
# View(trait_data)

species_in_traits <- trait_data$Species_common
species_in_detections <- colnames(abund2)
# Find items in list1 that are not in list2
missing_in_detections <- setdiff(species_in_traits, species_in_detections)
missing_in_detections
# Find items in list2 that are not in list1 (if needed)
missing_in_traits <- setdiff(species_in_detections, species_in_traits)
missing_in_traits
# colnames(abund2)
# View(trait_data2)
##////////////////////////////////////////////////////////////////

#Calculate functional diversity metrics with FD:dbFD----
## Calculate functional diversity metrics with FD:dbFD----
View(trait_data)
View(abund2)
nrow(trait_data)
ncol(abund2)

# Tests

# write.csv(abund2, "0_Data/Processed/abundance.csv")
# write.csv(trait_data, "0_Data/Processed/trait_test.csv")

# abund_test <- read_csv("0_Data/Processed/abund test.csv")
# trait_test <- read_csv("0_Data/Processed/trait_test.csv")
View(abund_test)
View(trait_test)
# Convert tibble to dataframe
trait_data <- as.data.frame(trait_data)
# abund_test <- as.matrix(abund_test)
# Set row names
rownames(trait_data) <- trait_data$Species_common

# Remove the original column, if desired
trait_data$Species_common <- NULL

# No sites can't have a single species
rows_with_all_zeros <- apply(abund2, 1, function(x) all(x == 0))
which(rows_with_all_zeros)

# Find rows where not all values are 1
rows_not_all_zeros <- apply(abund2, 1, function(x) !all(x == 0))

# Subset the dataframe to keep only those rows
abund_no_empty_sites <- abund2[rows_not_all_zeros, ]
abund_no_empty_sites <- as.matrix(abund_no_empty_sites)
View(trait_data)
write.csv(abund_no_empty_sites, "0_Data/Processed/abundance_no_missing_detections.csv")
# Dataframes need to be identical and ordered alphabetically
nrow(abund_no_empty_sites)

fd<- FD::dbFD(trait_data, abund_no_empty_sites)
# fd<- FD::dbFD(trait_test, abund_test)
head(fd, n=5)
?head()
## Bind functional diversity metrics with station data
fd_dataframe <- as.data.frame(fd)
# bd_funcDiv<-cbind(abund_no_empty_sites[1:1], fd_dataframe)

View(fd_dataframe)
write.csv(fd_dataframe, "0_Data/Processed/functional_diversity.csv" )

```

Now we have the function dicversity metrics, we can start doing some stats on it.

## Add covariates
```R
# How many sites have less than 3 species?
fd_df <- read_csv("0_Data/Processed/functional_diversity.csv")
covariates <- read_csv("0_Data/Processed/merged_covariates.csv")
dist_to_forest <- read_csv("0_Data/Processed/retn dist to nearest forest.csv")
dist_to_forest <- select(dist_to_forest, location, Dist_near_forest)
covariates <- merge(covariates, dist_to_forest, by = "location")

covariates <- covariates %>% select(-c("TEWA", "OSFL", "RCKI", "YRWA", "REVI", "WTSP"))
names(fd_df)[1] <- "location"

# Add amount edge
covariates$Edge <- ifelse(covariates$RETN_m2 != 0 & covariates$RETN_perimeter_m !=0, 
                            covariates$RETN_m2 / covariates$RETN_perimeter_m, 0)
covariates$Year_since_logging2 <- covariates$Year_since_logging ^2
# max(covariates$Edge) # 37.22
# Add patch presence
covariates <- covariates %>%
      mutate(Patch = ifelse(RETN_m2 > 0, 1, 0))

# Check the distribution of patch size
# ggplot(covariates, aes(x = RETN_m2)) +
  # geom_histogram()

# This data has a few really large retention pathces. Let;s get rid of those
covariates <- covariates |>
  filter(RETN_m2 < 12000)

# Check the distribution of patch size now -- better
# ggplot(covariates, aes(x = RETN_m2)) +
  # geom_histogram()

# Scale some of these predictors
predictors_to_scale <- c('RETN_m2', 'Year_since_logging', "Edge", "Year_since_logging2", "Dist_near_forest")
covariates[, predictors_to_scale] <- lapply(covariates[, predictors_to_scale], function(x) {
  (x - min(x, na.rm = TRUE)) / (max(x, na.rm = TRUE) - min(x, na.rm = TRUE))
})
View(covariates)

# Filter the sites in covariates so they match with fd_df
correct_sites <- fd_df$location
covariates_matching_sites <- covariates |>
                                filter(location %in% correct_sites)

nrow(covariates_matching_sites)
nrow(fd_df)

# 37 sites do not have any covariate data. These are likely becuase they didn't make the cut in terms of site quality.
# Exclude the sites that are not in covariate
sites_with_covs <- covariates_matching_sites$location
funcDiv_correct_sites <- fd_df |>
                          filter(location %in% sites_with_covs)
nrow(funcDiv_correct_sites)
nrow(covariates_matching_sites)
# write.csv(covariates_matching_sites, "0_Data/Processed/covariates_prepped_comm.csv" )
# Now these two are mathcing in length (368 sites)
# Reset the names os it is clear
Covariates <- covariates_matching_sites
FuncDiv <- funcDiv_correct_sites

# Avoid duplication in column names
FuncDiv_Covs <- cbind(Covariates, FuncDiv[, !names(FuncDiv) %in% names(Covariates)])
# write.csv(FuncDiv_Covs, "0_Data/Processed/functional_diversity_and_covs.csv")
View(FuncDiv_Covs)
# How many sites have less than 3 species?
?dbFD()

```

## Plots of observations
```R 
p1 <- ggplot(FuncDiv_Covs, aes(x = RETN_m2, y = FDiv)) +
  geom_point() +
  geom_smooth(method = "glm", method.args = list(family = "gaussian"))

p2 <- ggplot(FuncDiv_Covs, aes(x = Edge, y = FDiv)) +
  geom_point() +
  geom_smooth(method = "glm", method.args = list(family = "gaussian"))

# Combine the plots side by side
combined_plot <- p1 + p2 +
  plot_layout(widths = c(1, 1), heights = c(1,1))

# Print the combined plot
combined_plot

# nbsp: number of species in each community
FuncDiv |>
      filter(nbsp <= 2)

ggplot(FuncDiv_Covs, aes(x = Year_since_logging, y = nbsp, color = Veg_cat)) +
  geom_point() +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  labs(x = "Year Since Logging", y = "Number of Bird Species (nbsp)")

ggplot(FuncDiv_Covs, aes(x = RETN_m2, y = nbsp, color = Veg_cat)) +
  geom_point() +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  labs(x = "Patch area", y = "Number of Bird Species (nbsp)")

ggplot(FuncDiv_Covs, aes(x = Edge, y = nbsp, color = Veg_cat)) +
  geom_point() +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  labs(x = "Patch edge", y = "Number of Bird Species (nbsp)")

ggplot(FuncDiv_Covs, aes(x = Year_since_logging, y = FDiv, color = Veg_cat)) +
  geom_point() +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  labs(x = "Year Since Logging", y = "Functional diversity")

ggplot(FuncDiv_Covs, aes(x = RETN_m2, y = FDiv, color = Veg_cat)) +
  geom_point() +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  labs(x = "Patch area", y = "Functional diversity")

ggplot(FuncDiv_Covs, aes(x = Edge, y = FDiv, color = Veg_cat)) +
  geom_point() +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  labs(x = "Patch edge", y = "Functional diversity")

ggplot(FuncDiv_Covs, aes(x = Year_since_logging, y = FEve, color = Veg_cat)) +
  geom_point() +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  labs(x = "Year Since Logging", y = "Functional evenness")

ggplot(FuncDiv_Covs, aes(x = RETN_m2, y = FEve, color = Veg_cat)) +
  geom_point() +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  labs(x = "Patch area", y = "Functional evenness")

```


## Functional divergence: testing models
```R 
names(FuncDiv_Covs)

Func_diversity_glm0 <- glmmTMB(FDiv ~ Edge,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm0) # -926.1896
summary(Func_diversity_glm0)

# Best model so far
Func_diversity_glm0b <- glmmTMB(FDiv ~ RETN_m2,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm0b) # -923.6
summary(Func_diversity_glm0b)

Func_diversity_glm1 <- glmmTMB(FDiv ~ Edge + Year_since_logging,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm1) # -924.1918
summary(Func_diversity_glm1)

# Top model
Func_diversity_glm1b <- glmmTMB(FDiv ~ RETN_m2 + Year_since_logging,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm1b) # -921.6
summary(Func_diversity_glm1b)

Func_diversity_glm2 <- glmmTMB(FDiv ~ RETN_m2 + Year_since_logging + Veg_cat,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm2) # [1] -931.7684
summary(Func_diversity_glm2)

# Best model so far
Func_diversity_glm3 <- glmmTMB(FDiv ~ RETN_m2 + Year_since_logging + Dist_near_forest,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm3) # [1] -919.9633
summary(Func_diversity_glm3)

Func_diversity_glm3b <- glmmTMB(FDiv ~ Edge + Year_since_logging + Dist_near_forest,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm3b) # -922.4232
summary(Func_diversity_glm3b)

# Worse
Func_diversity_glm4 <- glmmTMB(FDiv ~ RETN_m2 + Dist_near_forest,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm4) # -921.9633
summary(Func_diversity_glm4)

Func_diversity_glm5 <- glmmTMB(FDiv ~ Edge + Year_since_logging + poly(Year_since_logging2),
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm5) # -925.2
summary(Func_diversity_glm5)

# better AIC, but nothing sig
Func_diversity_glm6 <- glmmTMB(FDiv ~ RETN_m2 + Year_since_logging*Patch + Dist_near_forest ,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm6) # -916.9502
summary(Func_diversity_glm6)

Func_diversity_glm6b <- glmmTMB(FDiv ~ Edge + Year_since_logging*Patch + Dist_near_forest ,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm6b) # -918.4892
summary(Func_diversity_glm6b)

Func_diversity_glm6 <- glmmTMB(FDiv ~ RETN_m2 + Year_since_logging*Patch + Dist_near_forest + Veg_cat,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm6) # -926.5568
summary(Func_diversity_glm6)

```

## Functional divergenge: comparing top models
```R  
Func_diversity_glm3 <- glmmTMB(FDiv ~ RETN_m2 + Year_since_logging + Dist_near_forest,
                        data = FuncDiv_Covs,
                        family = Gamma(link=log))
AIC(Func_diversity_glm3) # [1] -919.9633
summary(Func_diversity_glm3)
r.squaredGLMM(Func_diversity_glm3) #0.01015494 0.01015494
plot(simulateResiduals(Func_diversity_glm3)) # residuals good

# better AIC, but nothing sig
Func_diversity_glm6 <- glmmTMB(FDiv ~ RETN_m2 + Year_since_logging*Patch + Dist_near_forest ,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm6) # -916.9502
summary(Func_diversity_glm6)
r.squaredGLMM(Func_diversity_glm6) # 0.01298262 0.01298262
plot(simulateResiduals(Func_diversity_glm6)) # residuals good

Func_diversity_glm6b <- glmmTMB(FDiv ~ Edge + Year_since_logging*Patch + Dist_near_forest ,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm6b) # -918.4892
summary(Func_diversity_glm6b)
r.squaredGLMM(Func_diversity_glm6b) # 0.01737545 0.01737545
plot(simulateResiduals(Func_diversity_glm6b))


Func_diversity_glm6bre <- glmmTMB(FDiv ~ Edge + Year_since_logging*Patch + Dist_near_forest + (1|location),
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm6bre) # -916.4892
summary(Func_diversity_glm6bre)
r.squaredGLMM(Func_diversity_glm6bre) # 0.01737543 0.2199696
plot(simulateResiduals(Func_diversity_glm6b))

```

## Functional divergence: potting top model
```R
Func_diversity_glm6bre <- glmmTMB(FDiv ~ Edge + Year_since_logging*Patch + Dist_near_forest + (1|location),
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm6bre) # -916.4892
summary(Func_diversity_glm6bre)
func_div_summary <- summary(Func_diversity_glm6bre)

# Extract the coefficients table (fixed effects as an example)
coefficients_table <- as.data.frame(func_div_summary$coefficients$cond) # for conditional effects
coefficients_table

# Save the coefficients table to a CSV file
write.csv(coefficients_table, file.path("2_Outputs/Functional", "functional_divergence_summary.csv"), row.names=TRUE)

# use the model without random effects for predicitons
Func_diversity_glm6b <- glmmTMB(FDiv ~ Edge + Year_since_logging*Patch + Dist_near_forest ,
                        data = FuncDiv_Covs,
                        family = gaussian)
# Create a new data frame for predictions
predict_data_edge <- data.frame(
  Edge = seq(min(FuncDiv_Covs$Edge, na.rm = TRUE), 
            max(FuncDiv_Covs$Edge, na.rm = TRUE), length.out = 367),
  Dist_near_forest = mean(FuncDiv_Covs$Dist_near_forest, na.rm = TRUE),
  Year_since_logging = mean(FuncDiv_Covs$Year_since_logging, na.rm = TRUE),
  # Patch = 0)
  Patch = mean(FuncDiv_Covs$Patch, na.rm = TRUE))

# Predict using the model without a random effect
predicted_no_re <- predict(Func_diversity_glm6b, newdata = predict_data_edge, type = "response", se.fit = TRUE)

# Add predictions and confidence intervals to the data frame
predict_data_edge$lwr <- predicted_no_re$fit - 2*predicted_no_re$se.fit
predict_data_edge$upr <- predicted_no_re$fit + 2*predicted_no_re$se.fit
predict_data_edge$predicted <- predicted_no_re$fit
# View(predict_data_age2)

# Plotting harvest age
# Scaled back
predict_data_edge$Original_Edge <- predict_data_edge$Edge * 37.22

Edge_plot_scaled <- predict_data_edge %>%
  ggplot(aes(x = Original_Edge, y = predicted, group = 1)) +
  geom_ribbon(aes(ymin = lwr, ymax = upr), fill = 'grey', alpha = .4, linetype = 0) +
  geom_line() +
  geom_point(data = FuncDiv_Covs, 
            aes(x = Edge * 37.22, y = FDiv, group = 1), 
            size = 0.5,
            alpha = .3,
            position = "jitter") + # Adjust for actual data points if necessary
  theme_minimal() +
  ylab("Functional divergence") +
  xlab("Amount of edge (m)") +
  # scale_y_continuous(limits = c(min(predict_data_age2$lwr, na.rm = TRUE), max(predict_data_age2$upr, na.rm = TRUE))) +
  scale_x_continuous(limits = c(0, 40)) + # Explicitly set x-axis limits
  theme(legend.position = "none", 
        axis.text=element_text(size=12),
        axis.title=element_text(size=14))
print(Edge_plot_scaled)

ggsave(filename = file.path("2_Outputs/Functional", "Functional divergence and edge.png"), plot = Edge_plot_scaled, width = 5, height = 4)

```

Area and edge seem to have an effect on functional diversity, 
and year of harvest is a small effect but quadratic with a maximum around mid age range.


## Functional richness: testing models
```R 
names(FuncDiv_Covs)

Func_diversity_glm0 <- glmmTMB(FRic ~ Patch,
                        data = FuncDiv_Covs,
                        family = gaussian)
summary(Func_diversity_glm0)
AIC(Func_diversity_glm0) # -1739.724

Func_diversity_glm0 <- glmmTMB(FRic ~ RETN_m2,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm0) # -1741.914
summary(Func_diversity_glm0)

# Best AIC. Edge is p=0.05 !!!!!!!!!!!!!!!!!!!!!!!!
Func_diversity_glm0b <- glmmTMB(FRic ~ Edge,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm0b) # -1739.875
summary(Func_diversity_glm0b)

Func_diversity_glm1 <- glmmTMB(FRic ~ Edge + Year_since_logging,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm1) # -1743.441
summary(Func_diversity_glm1)

Func_diversity_glm1b <- glmmTMB(FRic ~ RETN_m2 + Year_since_logging,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm1b) # -1741.6
summary(Func_diversity_glm1b)

Func_diversity_glm2 <- glmmTMB(FRic ~ Edge + Year_since_logging+  Veg_cat,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm2) # [1] -1743.4
summary(Func_diversity_glm2)

# Worse
Func_diversity_glm3 <- glmmTMB(FRic ~ Edge + Year_since_logging + Dist_near_forest,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm3) # [1] -1744.984
summary(Func_diversity_glm3)


Func_diversity_glm4 <- glmmTMB(FRic ~ Edge + poly(Year_since_logging2),
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm4) # [1] -1743.676
summary(Func_diversity_glm4)

# Same as top model. nothing significant
Func_diversity_glm5 <- glmmTMB(FRic ~ Edge + Year_since_logging*Patch,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm5) # -1739.546
summary(Func_diversity_glm5)


Func_diversity_glm6 <- glmmTMB(FRic ~ Edge + Patch*Veg_cat,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm6) # [1] -1752.352
summary(Func_diversity_glm6)


Func_diversity_glm7 <- glmmTMB(FRic ~ Edge + Dist_near_forest,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm7) # -1743.412
summary(Func_diversity_glm7)


Func_diversity_glm8 <- glmmTMB(FRic ~ Edge + Year_since_logging + Dist_near_forest + poly(Year_since_logging2)
                                    + (1|location),
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm8) # -1741.353
summary(Func_diversity_glm8)

```

## Functional richness: comparing top models 
```R 
Func_diversity_glm0b <- glmmTMB(FRic ~ Edge,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm0b) # -1739.875
summary(Func_diversity_glm0b)
r.squaredGLMM(Func_diversity_glm0b) # 0.01088224 0.01088224
plot(simulateResiduals(Func_diversity_glm0b)) # Residuals are ok.

# Same as model without random effect
Func_diversity_glm0bre <- glmmTMB(FRic ~ Edge + (1|location),
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm0bre) # -1739.914
summary(Func_diversity_glm0bre)
r.squaredGLMM(Func_diversity_glm0bre) # 0.01088206 0.7668419
plot(simulateResiduals(Func_diversity_glm0bre)) # Residuals are ok.

Func_diversity_glm5 <- glmmTMB(FRic ~ Edge + Year_since_logging*Patch,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm5) # -1739.546
summary(Func_diversity_glm5)
r.squaredGLMM(Func_diversity_glm5) # 0.02123786 0.02123786
plot(simulateResiduals(hill_rich5b)) # Residuals are good.
```

## Funcitonal richness: plotting top model
```R 
Func_diversity_glm0b <- glmmTMB(FRic ~ Edge,
                        data = FuncDiv_Covs,
                        family = gaussian)
r.squaredGLMM(Func_diversity_glm0b)
  # Save the top model output
func_ric_summary <- summary(Func_diversity_glm0b)

# Extract the coefficients table (fixed effects as an example)
coefficients_table <- as.data.frame(func_ric_summary$coefficients$cond) # for conditional effects
coefficients_table

# Save the coefficients table to a CSV file
write.csv(coefficients_table, file.path("2_Outputs/Functional", "functional_richness_summary.csv"), row.names=TRUE)

# Create a new data frame for predictions
predict_data_edge <- data.frame(
  Edge = seq(min(FuncDiv_Covs$Edge, na.rm = TRUE), 
                           max(FuncDiv_Covs$Edge, na.rm = TRUE), length.out = 367))

# Predict using the model without a random effect
predicted_no_re <- predict(Func_diversity_glm0b, newdata = predict_data_edge, type = "response", se.fit = TRUE)

# Add predictions and confidence intervals to the data frame
predict_data_edge$lwr <- predicted_no_re$fit - 2*predicted_no_re$se.fit
predict_data_edge$upr <- predicted_no_re$fit + 2*predicted_no_re$se.fit
predict_data_edge$predicted <- predicted_no_re$fit
# View(predict_data_age2)

# Plotting harvest age
# Scaled back
predict_data_edge$Original_Edge <- predict_data_edge$Edge * 37.22

# Update plotting code
Edge_plot_scaled <- predict_data_edge %>%
  ggplot(aes(x = Original_Edge, y = predicted, group = 1)) +
  geom_ribbon(aes(ymin = lwr, ymax = upr), fill = 'grey', alpha = .4, linetype = 0) +
  geom_line() +
  geom_point(data = FuncDiv_Covs, 
            aes(x = Edge * 37.22, y = FRic, group = 1), 
            size = 0.5,
            alpha = .3,
            position = "jitter") + # Adjust for actual data points if necessary
  theme_minimal() +
  ylab("Functional richness") +
  xlab("Amount of edge (m)") +
  # scale_y_continuous(limits = c(min(predict_data_age2$lwr, na.rm = TRUE), max(predict_data_age2$upr, na.rm = TRUE))) +
  scale_x_continuous(limits = c(0, 40)) + # Explicitly set x-axis limits
  theme(legend.position = "none", 
        axis.text=element_text(size=12),
        axis.title=element_text(size=14))
# ?geom_point
print(Edge_plot_scaled)

ggsave(filename = file.path("2_Outputs/Functional", "Functional richness and Edge.png"), plot = Edge_plot_scaled, width = 5, height = 4)
```

## Functional evenness: testing models
```R 
hist(FuncDiv_Covs_no_na$FEvelogit)
FuncDiv_Covs_no_na <- FuncDiv_Covs %>% drop_na()
gamma_params(mean(FuncDiv_Covs_no_na$FEve2), sd(FuncDiv_Covs_no_na$FEve2), scale = FALSE)
beta_params(mean(FuncDiv_Covs_no_na$FEve2), sd(FuncDiv_Covs_no_na$FEve2))

hist(rgamma(n = 400, shape = 380, rate = 417))
hist(rbeta(n= 400, shape1 = 33, shape2 = 3.2))
?rbeta
?gamma_params
FuncDiv_Covs_no_na$FEve2 <- sqrt(FuncDiv_Covs_no_na$FEve)
FuncDiv_Covs_no_na$FEve

FuncDiv_Covs_no_na$FEvelogit <- logit(FuncDiv_Covs_no_na$FEve)

Func_diversity_glm0 <- glmmTMB(FEve ~ Edge,
                        data = FuncDiv_Covs,
                        family = Gamma(link=log))
AIC(Func_diversity_glm0) # -745.113
summary(Func_diversity_glm0)
plot(simulateResiduals(Func_diversity_glm0)) # residuasl have issues

# Best model so far
Func_diversity_glm0b <- glmmTMB(FEve ~ RETN_m2 + (1|location),
                        data = FuncDiv_Covs_no_na,
                        family = beta_family(link="logit"))
AIC(Func_diversity_glm0b) # -746.3939
summary(Func_diversity_glm0b)
plot(simulateResiduals(Func_diversity_glm0b))
?glmmTMB
# Best so far
Func_diversity_glm1 <- glmmTMB(FEve ~ Edge + Year_since_logging,
                        data = FuncDiv_Covs_no_na,
                        family = beta_family(link="logit"))
AIC(Func_diversity_glm1) # -743.3524
summary(Func_diversity_glm1)
plot(simulateResiduals(Func_diversity_glm1))

Func_diversity_glm1b <- glmmTMB(FEvelogit ~ RETN_m2 + Year_since_logging,
                        data = FuncDiv_Covs_no_na,
                        family = gaussian)
AIC(Func_diversity_glm1b) # -744.5948
summary(Func_diversity_glm1b)
plot(simulateResiduals(Func_diversity_glm1b))

# Best
Func_diversity_glm2 <- glmmTMB(FEve ~ RETN_m2 + Year_since_logging + Veg_cat,
                        data = FuncDiv_Covs,
                        family = Gamma(link=log))
AIC(Func_diversity_glm2) # -740.6377
summary(Func_diversity_glm2)

# Same as top model
Func_diversity_glm2b <- glmmTMB(FEve ~ Edge + Year_since_logging + Veg_cat,
                        data = FuncDiv_Covs,
                        family = Gamma(link=log))
AIC(Func_diversity_glm2b) # -739.3941
summary(Func_diversity_glm2b)

# Best model so far
Func_diversity_glm3 <- glmmTMB(FEve ~ RETN_m2 + Year_since_logging + Dist_near_forest,
                        data = FuncDiv_Covs,
                        family = Gamma(link=log))
AIC(Func_diversity_glm3) # -744.5676
summary(Func_diversity_glm3)

Func_diversity_glm3b <- glmmTMB(FEve ~ Edge + Year_since_logging + Dist_near_forest,
                        data = FuncDiv_Covs,
                        family = Gamma(link=log))
AIC(Func_diversity_glm3b) # -743.234
summary(Func_diversity_glm3b)
plot(simulateResiduals(Func_diversity_glm3b)) # residuasl have issues


# Worse
Func_diversity_glm4 <- glmmTMB(FEve ~ RETN_m2 + Dist_near_forest,
                        data = FuncDiv_Covs,
                        family = Gamma(link=log))
AIC(Func_diversity_glm4) # -746.3677
summary(Func_diversity_glm4)

Func_diversity_glm5 <- glmmTMB(FEve ~ Edge + Year_since_logging + poly(Year_since_logging2),
                        data = FuncDiv_Covs,
                        family = Gamma(link=log))
AIC(Func_diversity_glm5) # -741.5367
summary(Func_diversity_glm5)

# 
Func_diversity_glm6 <- glmmTMB(FEve ~ RETN_m2 + Year_since_logging*Patch + Dist_near_forest ,
                        data = FuncDiv_Covs,
                        family = Gamma(link=log))
AIC(Func_diversity_glm6) # -740.7507
summary(Func_diversity_glm6)

# Same as top model
Func_diversity_glm6b <- glmmTMB(FEve ~ Edge + Year_since_logging*Patch + Dist_near_forest ,
                        data = FuncDiv_Covs,
                        family = Gamma(link=log))
AIC(Func_diversity_glm6b) # -739.9092
summary(Func_diversity_glm6b)
plot(simulateResiduals(Func_diversity_glm6b)) # residuasl have issues

# New best
Func_diversity_glm6 <- glmmTMB(FEve ~ RETN_m2 + Year_since_logging*Patch + Dist_near_forest + Veg_cat,
                        data = FuncDiv_Covs,
                        family = Gamma(link=log))
AIC(Func_diversity_glm6) # -736.73
summary(Func_diversity_glm6)

# Same as top
Func_diversity_glm6b <- glmmTMB(FEve ~ Edge + Year_since_logging*Patch + Dist_near_forest + Veg_cat,
                        data = FuncDiv_Covs,
                        family = Gamma(link=log))
AIC(Func_diversity_glm6b) # -735.9629
summary(Func_diversity_glm6b)

# same as top
Func_diversity_glm7 <- glmmTMB(FEve ~ RETN_m2 + Year_since_logging*Patch + Veg_cat,
                        data = FuncDiv_Covs,
                        family = Gamma(link=log))
AIC(Func_diversity_glm7) # -737.0806
summary(Func_diversity_glm7)

# same as top
Func_diversity_glm7b <- glmmTMB(FEve ~ Edge + Year_since_logging*Patch + Veg_cat,
                        data = FuncDiv_Covs,
                        family = Gamma(link=log))
AIC(Func_diversity_glm7b) # -736.3906
summary(Func_diversity_glm7b)

# New best
Func_diversity_glm8b <- glmmTMB(FEve ~ Edge + Year_since_logging*Patch + Veg_cat*Patch,
                        data = FuncDiv_Covs,
                        family = Gamma(link=log))
AIC(Func_diversity_glm8b) # -733.0898
summary(Func_diversity_glm8b)

Func_diversity_glm8a <- glmmTMB(FEve ~ RETN_m2 + Year_since_logging*Patch + Veg_cat*Patch,
                        data = FuncDiv_Covs,
                        family = Gamma(link=log))
AIC(Func_diversity_glm8a) # -733.7924
summary(Func_diversity_glm8a)

Func_diversity_glm9 <- glmmTMB(FEve ~ RETN_m2 + Year_since_logging + Veg_cat*Patch,
                        data = FuncDiv_Covs,
                        family = Gamma(link=log))
AIC(Func_diversity_glm9) # -735.593
summary(Func_diversity_glm9)

Func_diversity_glm9b <- glmmTMB(FEve ~ Edge + Year_since_logging + Veg_cat*Patch,
                        data = FuncDiv_Covs,
                        family = Gamma(link=log))
AIC(Func_diversity_glm9b) # -734.868
summary(Func_diversity_glm9b)

Func_diversity_glm10 <- glmmTMB(FEve ~ Edge + Year_since_logging + Veg_cat*Patch + poly(Year_since_logging2),
                        data = FuncDiv_Covs,
                        family = Gamma(link=log))
AIC(Func_diversity_glm10) # -733.255
summary(Func_diversity_glm10)

Func_diversity_glm11 <- glmmTMB(FEve ~ Edge + Veg_cat*Patch + poly(Year_since_logging2),
                        data = FuncDiv_Covs,
                        family = Gamma(link=log))
AIC(Func_diversity_glm11) # -734.8162
summary(Func_diversity_glm11)

Func_diversity_glm12 <- glmmTMB(FEve ~ Edge + Veg_cat*Patch + poly(Year_since_logging2),
                        data = FuncDiv_Covs,
                        family = Gamma(link=log))
AIC(Func_diversity_glm11) # -734.8162
summary(Func_diversity_glm11)

```

## Functional divergenge: comparing top models
```R 
# New best
Func_diversity_glm8b <- glmmTMB(FEve ~ Edge + Year_since_logging*Patch + Veg_cat*Patch,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm8b) # -733.0898
summary(Func_diversity_glm8b)
r.squaredGLMM(Func_diversity_glm8b) # 0.02819857 0.02819857
plot(simulateResiduals(Func_diversity_glm8b)) # residuals have some issues

Func_diversity_glm8a <- glmmTMB(FEve ~ RETN_m2 + Year_since_logging*Patch + Veg_cat*Patch,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm8a) # -733.7924
summary(Func_diversity_glm8a)
r.squaredGLMM(Func_diversity_glm8a) # 0.03017532 0.03017532
plot(simulateResiduals(Func_diversity_glm8a)) ## residuals have some issues

Func_diversity_glm9b <- glmmTMB(FEve ~ Edge + Year_since_logging + Veg_cat*Patch,
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm9b) # -734.868
summary(Func_diversity_glm9b)
r.squaredGLMM(Func_diversity_glm9b) # 0.02757374 0.02757374
plot(simulateResiduals(Func_diversity_glm9b)) # residuals have some issues

Func_diversity_glm9bre <- glmmTMB(FEve ~ Edge + Year_since_logging + Veg_cat*Patch + (1|location),
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm9bre) # -732.868
summary(Func_diversity_glm9bre)
r.squaredGLMM(Func_diversity_glm9bre) # 0.02757358 0.330473
plot(simulateResiduals(Func_diversity_glm9bre)) # stil issues in the residuals

Func_diversity_glm10 <- glmmTMB(FEve ~ Edge + Year_since_logging + Veg_cat*Patch + poly(Year_since_logging2),
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm10) # -733.255
summary(Func_diversity_glm10)
r.squaredGLMM(Func_diversity_glm10) #  0.02866387 0.02866387
plot(simulateResiduals(Func_diversity_glm10)) # residuals have some issues

Func_diversity_glm11 <- glmmTMB(FEve ~ Edge + Veg_cat*Patch + poly(Year_since_logging2),
                        data = FuncDiv_Covs,
                        family = gaussian)
AIC(Func_diversity_glm11) # -734.8162
summary(Func_diversity_glm11)
r.squaredGLMM(Func_diversity_glm11) # 0.02742791 0.027427
plot(simulateResiduals(Func_diversity_glm11)) # residuals  have some issues



```

# Single species metrics
## Load data
```R  
abundance <- read_csv("0_Data/Processed/community_abundance_by_location.csv")
covariates <- read_csv("0_Data/Processed/covariates_prepped_comm.csv")
max(covariates$RETN_m2)
Abund_Covs <- merge(abundance, covariates, by = "location")
```

Out of 18 species, Patch Area is positive for 3: LEFL, WAVI, YEWA.
## Dredge for each species
```R 
sum(is.na(Abund_Covs)) # 3 Nas
Abund_Covs <- Abund_Covs %>% drop_na()
Abund_Covs$Veg_cat <- as_factor(Abund_Covs$Veg_cat)
Abund_Covs$Patch <- as_factor(Abund_Covs$Patch)
View(Abund_Covs)
length(Abund_Covs$Year_since_logging2)#366
species_list <- c("ALFL", 'AMRE', 'BTNW', 'CHSP', 'COYE', 'HETH', 'LEFL', 'LISP', 'MOWA', 'REVI', 'RCKI', 'WAVI', 'WTSP', 'SWTH', 'YEWA', 'YRWA', 'TEWA', 'OSFL')

options(na.action = "na.fail") # There are no Nas in the dataset, so this just ensures the dredge() function behaves as expected

for (bird in species_list) {
  edge_formula_str <- paste(bird, "~  poly(Year_since_logging2) + Year_since_logging:Patch + Dist_near_forest + Edge + Veg_cat + Year_since_logging + Patch")
  edge_gm <- glm(as.formula(edge_formula_str), 
                 data = Abund_Covs, 
                 family = poisson)            
  
  area_formula_str <- paste(bird, "~ poly(Year_since_logging2) + Year_since_logging:Patch + Dist_near_forest + RETN_m2 + Veg_cat + Year_since_logging + Patch")
  area_gm <- glm(as.formula(area_formula_str),
                data = Abund_Covs,
                family = poisson)
  
  dredge_edge <- dredge(global.model = edge_gm, rank = 'AICc', extra = list(
    "R^2", "*" = function(x) {
        s <- summary(x)
        c(Rsq = s$r.squared, adjRsq = s$adj.r.squared,
            F = s$fstatistic[[1]])
    }))

  dredge_area <- dredge(global.model = area_gm, rank = 'AICc', extra = list(
    "R^2", "*" = function(x) {
        s <- summary(x)
        c(Rsq = s$r.squared, adjRsq = s$adj.r.squared,
            F = s$fstatistic[[1]])
    }))

  edge_top <- subset(dredge_edge, delta < 2)
  edge_top <- as.data.frame(edge_top)

  area_top <- subset(dredge_area, delta < 2)
  area_top <- as.data.frame(area_top)

  write.csv(edge_top, glue("2_Outputs/Single species/Dredge tables/{bird}_edge.csv"))
  write.csv(area_top, glue("2_Outputs/Single species/Dredge tables/{bird}_area.csv"))
}
```

## Top models for each species
Covariates to choose from:
poly(Year_since_logging2) + Year_since_logging*Patch + Dist_near_forest + RETN_m2 + Veg_cat
```R 
ALFL <- glmmTMB(ALFL ~ Dist_near_forest + poly(Year_since_logging2) + Year_since_logging*Patch,
                data = Abund_Covs,
                family = poisson)
# summary(ALFL)
AIC(ALFL)
plot(simulateResiduals(ALFL)) # residuals good
coefficients_table <- as.data.frame(summary(ALFL)$coefficients$cond) 
write.csv(coefficients_table, file.path("2_Outputs/Single species/Model summaries", "ALFL_summary.csv"), row.names=TRUE)

AMRE <- glmmTMB(AMRE ~ Dist_near_forest + poly(Year_since_logging2) + Veg_cat +Year_since_logging,
                data = Abund_Covs,
                family = poisson)
summary(AMRE)
plot(simulateResiduals(AMRE)) # residuals good
coefficients_table <- as.data.frame(summary(AMRE)$coefficients$cond) 
write.csv(coefficients_table, file.path("2_Outputs/Single species/Model summaries", "AMRE_summary.csv"), row.names=TRUE)

# No BTWN: models did not converge, and doesnt make that much sense. Too sensitive.

CHSP <- glmmTMB(CHSP ~ Dist_near_forest + poly(Year_since_logging2) +Year_since_logging,
                data = Abund_Covs,
                family = poisson)
summary(CHSP)
plot(simulateResiduals(CHSP)) # residuals good
coefficients_table <- as.data.frame(summary(CHSP)$coefficients$cond) 
write.csv(coefficients_table, file.path("2_Outputs/Single species/Model summaries", "CHSP_summary.csv"), row.names=TRUE)

COYE <- glmmTMB(COYE ~ Dist_near_forest + poly(Year_since_logging2) +Veg_cat +Year_since_logging*Patch,
                data = Abund_Covs,
                family = poisson)
summary(COYE)
plot(simulateResiduals(COYE)) # residuals good
coefficients_table <- as.data.frame(summary(COYE)$coefficients$cond) 
write.csv(coefficients_table, file.path("2_Outputs/Single species/Model summaries", "COYE_summary.csv"), row.names=TRUE)

HETH <- glmmTMB(HETH ~ Dist_near_forest + Edge + poly(Year_since_logging2) +Veg_cat +Year_since_logging+Patch,
                data = Abund_Covs,
                family = poisson)
summary(HETH)
plot(simulateResiduals(HETH)) # residuals good
coefficients_table <- as.data.frame(summary(HETH)$coefficients$cond) 
write.csv(coefficients_table, file.path("2_Outputs/Single species/Model summaries", "HETH_summary.csv"), row.names=TRUE)

LEFL <- glmmTMB(LEFL ~ Dist_near_forest + RETN_m2 +Veg_cat +Year_since_logging,
                data = Abund_Covs,
                family = poisson)
summary(LEFL)
plot(simulateResiduals(LEFL)) # residuals good
coefficients_table <- as.data.frame(summary(LEFL)$coefficients$cond) 
write.csv(coefficients_table, file.path("2_Outputs/Single species/Model summaries", "LEFL_summary.csv"), row.names=TRUE)

LISP <- glmmTMB(LISP ~ Patch + poly(Year_since_logging2) +Year_since_logging,
                data = Abund_Covs,
                family = poisson)
summary(LISP)
plot(simulateResiduals(LISP)) # residuals good
coefficients_table <- as.data.frame(summary(LISP)$coefficients$cond) 
write.csv(coefficients_table, file.path("2_Outputs/Single species/Model summaries", "LISP_summary.csv"), row.names=TRUE)

MOWA <- glmmTMB(MOWA ~ poly(Year_since_logging2) + RETN_m2 + Veg_cat,
                data = Abund_Covs,
                family = poisson)
summary(MOWA)
plot(simulateResiduals(MOWA)) # residuals good
coefficients_table <- as.data.frame(summary(MOWA)$coefficients$cond) 
write.csv(coefficients_table, file.path("2_Outputs/Single species/Model summaries", "MOWA_summary.csv"), row.names=TRUE)

OSFL <- glmmTMB(OSFL ~ Dist_near_forest + Edge + Veg_cat + Year_since_logging,
                data = Abund_Covs,
                family = poisson)
summary(OSFL)
plot(simulateResiduals(OSFL)) # residuals good
coefficients_table <- as.data.frame(summary(OSFL)$coefficients$cond) 
write.csv(coefficients_table, file.path("2_Outputs/Single species/Model summaries", "OSFL_summary.csv"), row.names=TRUE)

OSFL <- glmmTMB(OSFL ~ Dist_near_forest + Edge + Veg_cat + Year_since_logging,
                data = Abund_Covs,
                family = poisson)
summary(OSFL)
plot(simulateResiduals(OSFL)) # residuals good
coefficients_table <- as.data.frame(summary(OSFL)$coefficients$cond) 
write.csv(coefficients_table, file.path("2_Outputs/Single species/Model summaries", "OSFL_summary.csv"), row.names=TRUE)

RCKI <- glmmTMB(RCKI ~ Dist_near_forest + Edge + Patch + poly(Year_since_logging2) + Veg_cat + Year_since_logging,
                data = Abund_Covs,
                family = poisson)
summary(RCKI)
plot(simulateResiduals(RCKI)) # residuals good
coefficients_table <- as.data.frame(summary(RCKI)$coefficients$cond) 
write.csv(coefficients_table, file.path("2_Outputs/Single species/Model summaries", "RCKI_summary.csv"), row.names=TRUE)

REVI <- glmmTMB(REVI ~ Dist_near_forest + poly(Year_since_logging2) + Veg_cat + Year_since_logging,
                data = Abund_Covs,
                family = poisson)
summary(REVI)
plot(simulateResiduals(REVI)) # residuals good
coefficients_table <- as.data.frame(summary(REVI)$coefficients$cond) 
write.csv(coefficients_table, file.path("2_Outputs/Single species/Model summaries", "REVI_summary.csv"), row.names=TRUE)

SWTH <- glmmTMB(SWTH ~ Dist_near_forest + poly(Year_since_logging2) + Veg_cat + Year_since_logging,
                data = Abund_Covs,
                family = poisson)
summary(SWTH)
plot(simulateResiduals(SWTH)) # residuals good
coefficients_table <- as.data.frame(summary(SWTH)$coefficients$cond) 
write.csv(coefficients_table, file.path("2_Outputs/Single species/Model summaries", "SWTH_summary.csv"), row.names=TRUE)

TEWA <- glmmTMB(TEWA ~ Dist_near_forest + RETN_m2 + poly(Year_since_logging2) + Veg_cat + Year_since_logging*Patch,
                data = Abund_Covs,
                family = poisson)
summary(TEWA)
plot(simulateResiduals(TEWA)) # residuals good
coefficients_table <- as.data.frame(summary(TEWA)$coefficients$cond) 
write.csv(coefficients_table, file.path("2_Outputs/Single species/Model summaries", "TEWA_summary.csv"), row.names=TRUE)

WAVI <- glmmTMB(WAVI ~ Dist_near_forest + RETN_m2,
                data = Abund_Covs,
                family = poisson)
summary(WAVI)
plot(simulateResiduals(WAVI)) # residuals good
coefficients_table <- as.data.frame(summary(WAVI)$coefficients$cond) 
write.csv(coefficients_table, file.path("2_Outputs/Single species/Model summaries", "WAVI_summary.csv"), row.names=TRUE)

WTSP <- glmmTMB(WTSP ~ Dist_near_forest + Edge + poly(Year_since_logging2) + Veg_cat + Year_since_logging,
                data = Abund_Covs,
                family = poisson)
summary(WTSP)
plot(simulateResiduals(WTSP)) # residuals good
coefficients_table <- as.data.frame(summary(WTSP)$coefficients$cond) 
write.csv(coefficients_table, file.path("2_Outputs/Single species/Model summaries", "WTSP_summary.csv"), row.names=TRUE)

YEWA <- glmmTMB(YEWA ~ RETN_m2 + Veg_cat + Patch,
                data = Abund_Covs,
                family = poisson)
summary(YEWA)
plot(simulateResiduals(YEWA)) # residuals good
coefficients_table <- as.data.frame(summary(YEWA)$coefficients$cond) 
write.csv(coefficients_table, file.path("2_Outputs/Single species/Model summaries", "YEWA_summary.csv"), row.names=TRUE)

YRWA <- glmmTMB(YRWA ~ Dist_near_forest + Edge + poly(Year_since_logging2) + Veg_cat + Year_since_logging,
                data = Abund_Covs,
                family = poisson)
summary(YRWA)
plot(simulateResiduals(YRWA)) # residuals good
coefficients_table <- as.data.frame(summary(YRWA)$coefficients$cond) 
write.csv(coefficients_table, file.path("2_Outputs/Single species/Model summaries", "YRWA_summary.csv"), row.names=TRUE)
?glmmTMB

```

## Highlighted species: area plots
```R 
# LEFL, WAVI, YEWA for RETN_m2
# COYE, TEWA for Year*patch
# omit categorical veg
LEFL <- glmmTMB(LEFL ~ Dist_near_forest + RETN_m2 + Veg_cat + Year_since_logging,
                data = Abund_Covs,
                family = poisson)
LEFLnoveg <- glmmTMB(LEFL ~ Dist_near_forest + RETN_m2 + Year_since_logging,
                data = Abund_Covs,
                family = poisson)
Abund_Covs$Patch <- as.numeric(Abund_Covs$Patch)
WAVI <- glmmTMB(WAVI ~ Dist_near_forest + RETN_m2,
                data = Abund_Covs,
                family = poisson)

# Create a new data frame for predictions
# predict_data_edge <- data.frame(
#   RETN_m2 = seq(min(Abund_Covs$RETN_m2, na.rm = TRUE), 
#               max(Abund_Covs$RETN_m2, na.rm = TRUE), length.out = 400),
#   Dist_near_forest = mean(Abund_Covs$Dist_near_forest, na.rm = TRUE),
#   Year_since_logging = mean(Abund_Covs$Year_since_logging, na.rm = TRUE))
Abund_Covs$Patch <- as.numeric(Abund_Covs$Patch)
predict_data_edge <- data.frame(
  RETN_m2 = seq(min(Abund_Covs$RETN_m2, na.rm = TRUE), 
              max(Abund_Covs$Year_since_logging2, na.rm = TRUE), length.out = 400),
  Dist_near_forest = mean(Abund_Covs$Dist_near_forest, na.rm = TRUE),
  Year_since_logging = mean(Abund_Covs$Year_since_logging, na.rm = TRUE),
  Year_since_logging2 = mean(Abund_Covs$Year_since_logging2, na.rm = TRUE),
  Patch = mean(Abund_Covs$Patch, na.rm = TRUE))

# Predict using the model without a random effect
predicted_fit <- predict(COYEnoveg, newdata = predict_data_edge, type = "response", se.fit = TRUE)

# Add predictions and confidence intervals to the data frame
predict_data_edge$lwr <- predicted_fit$fit - 2*predicted_fit$se.fit
predict_data_edge$upr <- predicted_fit$fit + 2*predicted_fit$se.fit
predict_data_edge$predicted <- predicted_fit$fit

# Scaled back
# Assuming 'min_x' and 'max_x' are the original minimum and maximum values for your predictor
min_x <- 0   # Replace with actual minimum if different
max_x <- 12000  # Replace with actual maximum

# Transforming the scaled values back to the original scale
predict_data_edge$area <- lapply(predict_data_edge$RETN_m, function(scaled) {
  (scaled * (max_x - min_x)) + min_x
})
predict_data_edge$area <- as.numeric(as.character(predict_data_edge$area))

area_plot_scaled <- predict_data_edge %>%
  ggplot(aes(x = area, y = predicted, group = 1)) +
  geom_ribbon(aes(ymin = lwr, ymax = upr), fill = 'grey', alpha = .4, linetype = 0) +
  geom_line() +
  geom_point(data = Abund_Covs, 
            aes(x = RETN_m2 * 12000, y = COYE, group = 1), 
            size = 0.5,
            alpha = .3,
            position = "jitter") +
  theme_minimal() +
  ylab("Common Yellowthroat abundance") +
  xlab(expression("Area (" * m^2 * ")")) +
  scale_x_continuous(limits = c(0, 12000)) + 
  # scale_y_continuous(limits = c(min(predict_data_age2$lwr, na.rm = TRUE), max(predict_data_age2$upr, na.rm = TRUE))) +
  # scale_x_continuous(limits = c(0, 12000)) + # Explicitly set x-axis limits
  theme(legend.position = "none", 
        axis.text=element_text(size=12),
        axis.title=element_text(size=14))

print(area_plot_scaled)

ggsave(filename = file.path("2_Outputs/Single species/Area plots", "LEFL and area.png"), plot = area_plot_scaled, width = 5, height = 4)


```

## Highlighted species: harvest age plots
```R 


```

### Other stuff, omit
```R 
abundance <- read_csv("0_Data/Processed/community_abundance_by_location.csv")
covariates <- read_csv("0_Data/Processed/covariates_prepped_comm.csv")
Abund_Covs <- merge(abundance, covariates, by = "location")

ALFL <- glmmTMB(ALFL ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(ALFL)


AMRE <- glmmTMB(AMRE ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(AMRE)

BTNW <- glmmTMB(BTNW ~  Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(BTNW)

CHSP <- glmmTMB(CHSP ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(CHSP)

COYE <- glmmTMB(COYE ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(COYE)

HETH <- glmmTMB(HETH ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(HETH)

# So far, only one wehere RETN_m2 matter. It's positive for this dude
LEFL <- glmmTMB(LEFL ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(LEFL) # AIC: 220

# Convergence issue. Only 4 sites with more than 1 LCSP
LCSP <- glmmTMB(LCSP ~ Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(LCSP)
nrow(Abund_Covs |> filter(LCSP >0)) #4

LISP <- glmmTMB(LISP ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(LISP)

MOWA <- glmmTMB(MOWA ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(MOWA)

OVEN <- glmmTMB(OVEN ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(OVEN) # AIC: 238

# No PHVI in the data
PHVI <- glmmTMB(PHVI ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(PHVI)

REVI <- glmmTMB(REVI ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(REVI)

RCKI <- glmmTMB(RCKI ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(RCKI)

SWTH <- glmmTMB(SWTH ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(SWTH)

# RETN_m2 positive
WAVI <- glmmTMB(WAVI ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(WAVI) # AIC 482

WTSP <- glmmTMB(WTSP ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(WTSP)

WIWR <- glmmTMB(WIWR ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(WIWR)

# RETN positive
YEWA <- glmmTMB(YEWA ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(YEWA) # ACID 187, better than Edge

YRWA <- glmmTMB(YRWA ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(YRWA) # AIC 570

TEWA <- glmmTMB(TEWA ~ poly(Year_since_logging2) + Year_since_logging*Patch + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(TEWA)

OSFL <- glmmTMB(OSFL ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(OSFL)

```

# Single species metrics: Patch edge 
Out of 18 species, Patch Edge is positive for 4 LEFL, WAVI, YEWA, YRWA
and negative for OVEN.
```R 
ALFL <- glmmTMB(ALFL ~ poly(Year_since_logging2) + Year_since_logging + Edge + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(ALFL)


AMRE <- glmmTMB(AMRE ~ poly(Year_since_logging2) + Year_since_logging + Edge + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(AMRE)

BTNW <- glmmTMB(BTNW ~  Year_since_logging + Edge + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(BTNW)

CHSP <- glmmTMB(CHSP ~ poly(Year_since_logging2) + Year_since_logging + Edge + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(CHSP)

COYE <- glmmTMB(COYE ~ poly(Year_since_logging2) + Year_since_logging + Edge + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(COYE)

HETH <- glmmTMB(HETH ~ poly(Year_since_logging2) + Year_since_logging + Edge + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(HETH)

# So far, only one where Edge matter. It's positive for this dude
LEFL <- glmmTMB(LEFL ~ poly(Year_since_logging2) + Year_since_logging + Edge + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(LEFL) # AIC: 227

# Convergence issue. Only 4 sites with more than 1 LCSP
LCSP <- glmmTMB(LCSP ~ Year_since_logging + Edge + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(LCSP)
nrow(Abund_Covs |> filter(LCSP >0)) #4

LISP <- glmmTMB(LISP ~ poly(Year_since_logging2) + Year_since_logging + Edge + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(LISP)

MOWA <- glmmTMB(MOWA ~ poly(Year_since_logging2) + Year_since_logging + Edge + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(MOWA)

# Edge bad
OVEN <- glmmTMB(OVEN ~ poly(Year_since_logging2) + Year_since_logging + Edge + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(OVEN)# AIC: 237

# No PHVI in the data
PHVI <- glmmTMB(PHVI ~ poly(Year_since_logging2) + Year_since_logging + Edge + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(PHVI)

REVI <- glmmTMB(REVI ~ poly(Year_since_logging2) + Year_since_logging + Edge + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(REVI)

RCKI <- glmmTMB(RCKI ~ poly(Year_since_logging2) + Year_since_logging + Edge + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(RCKI)

SWTH <- glmmTMB(SWTH ~ poly(Year_since_logging2) + Year_since_logging + Edge + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(SWTH)

# Edge positive
WAVI <- glmmTMB(WAVI ~ poly(Year_since_logging2) + Year_since_logging + Edge + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(WAVI) # AIC 428, better than RETN_m2 model

WTSP <- glmmTMB(WTSP ~ poly(Year_since_logging2) + Year_since_logging + Edge + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(WTSP)

WIWR <- glmmTMB(WIWR ~ poly(Year_since_logging2) + Year_since_logging + Edge + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(WIWR)

# Edge positive
YEWA <- glmmTMB(YEWA ~ poly(Year_since_logging2) + Year_since_logging + Edge + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(YEWA) # AIC 189

# Edge positive
YRWA <- glmmTMB(YRWA ~ poly(Year_since_logging2) + Year_since_logging + Edge + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(YRWA) # ACI 569

GRJA
```

# Response from birds of prey, and nest eaters?
```R 
CAJA <- glmmTMB(CAJA ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(CAJA)

AMCR <- glmmTMB(AMCR ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(AMCR)

DOWO <- glmmTMB(DOWO ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(DOWO)

PIWO <- glmmTMB(PIWO ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(PIWO)

RUGR <- glmmTMB(RUGR ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(RUGR)

BLJA <- glmmTMB(BLJA ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(BLJA)

# Likes the retentin patches
CORA <- glmmTMB(CORA ~ poly(Year_since_logging2) + Year_since_logging + RETN_m2 + Dist_near_forest,
                data = Abund_Covs,
                family = poisson)
summary(CORA)

```
